use_frameworks!

target 'Sniper_Example' do
  pod 'Sniper', :path => '../'

  target 'Sniper_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
